# Simplified Docker Compose for Portainer Stack Deployment
# Copy this content into Portainer's Stack editor

version: '3.8'

services:
  cider-remote-server:
    # If using pre-built image from registry:
    # image: your-registry/cider-remote-server:latest

    # If building from repository in Portainer:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: cider-remote-server
    restart: unless-stopped

    ports:
      - "3001:3001"

    environment:
      # Change these values as needed
      - PORT=3001
      - NODE_ENV=production

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Basic resource limits
    deploy:
      resources:
        limits:
          memory: 512M

    networks:
      - cider-network

networks:
  cider-network:
    driver: bridge
